# Generated by Django 4.0.4 on 2022-05-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transaction_symbol_name_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holdings',
            old_name='symbol',
            new_name='symbol_name',
        ),
    ]
