# Generated by Django 4.0.4 on 2022-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_symbol_holdings_symbol_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='amount',
        ),
        migrations.AddField(
            model_name='holdings',
            name='amount_spent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holdings',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addreminder',
            name='Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
