# Generated by Django 4.0.4 on 2022-05-07 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_remove_holdings_amount_holdings_amount_spent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdings',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='holdings',
            unique_together={('user', 'symbol_name')},
        ),
        migrations.AlterModelTable(
            name='holdings',
            table='Holdings',
        ),
    ]
