# Generated by Django 4.0.4 on 2022-05-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_holdings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdings',
            options={},
        ),
    ]
