# Generated by Django 4.0.4 on 2022-05-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_holdings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='id',
        ),
        migrations.AddField(
            model_name='holdings',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
