# Generated by Django 4.0.4 on 2022-05-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_holdings_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='auto_increment_id',
        ),
    ]
