# Generated by Django 4.0.4 on 2022-05-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_holdings_auto_increment_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holdings',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='holdings',
            table=None,
        ),
    ]
