# Generated by Django 4.0.4 on 2022-05-08 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_holdings_id_alter_holdings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('portfolio_value', models.FloatField()),
                ('portfolio_value_24', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
