# Generated by Django 3.2.13 on 2022-05-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_dailystats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystats',
            name='portfolio_value_24',
        ),
    ]
