# Generated by Django 3.2.13 on 2022-05-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_dailystats_portfolio_value_24'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addreminder',
            name='buy_sell',
        ),
        migrations.AddField(
            model_name='addreminder',
            name='Above_below',
            field=models.CharField(choices=[('Above', 'Above'), ('Below', 'Below')], default='buy', max_length=20),
        ),
    ]
